name: feature-pipeline
on: [push]
jobs:
  feature-pipeline:
    uses: Rohith-rdaws/workflows/.github/workflows/feature-nodejs-pipeline.yaml@main
    with:
      project: roboshop
      component: catalogue
      environment: dev
      